### ISSUE TITLE
Member who reacted could not be found => TypeError: Cannot read property 'addRole' of null

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/physicsbot#9]
Logs for mysterious user from 14:47:09 to 14:52:49:
```
[ 28/11/2018T14:47:09 ][ REACTION_ADD ]@( ████████, physik, 513534396524134420 )
/home/pi/physicsbot/src/bot.js:101
        .addRole(associatedRole.id)
         ^

TypeError: Cannot read property 'addRole' of null
```
```
[ 28/11/2018T14:52:09 ][ REACTION_ADD ]@( ████████, info, 513534396524134420 )
/home/pi/physicsbot/src/bot.js:101
        .addRole(associatedRole.id)
         ^

TypeError: Cannot read property 'addRole' of null
```
```
[ 28/11/2018T14:52:16 ][ REACTION_ADD ]@( ████████, la, 513534396524134420 )
/home/pi/physicsbot/src/bot.js:101
        .addRole(associatedRole.id)
         ^

TypeError: Cannot read property 'addRole' of null
```
```
[ 28/11/2018T14:52:49 ][ REACTION_ADD ]@( ████████, la, 513534396524134420 )
/home/pi/physicsbot/src/bot.js:101
        .addRole(associatedRole.id)
         ^

TypeError: Cannot read property 'addRole' of null
```
But suddenly, it worked:
```
[ 28/11/2018T14:53:05 ][ REACTION_ADD ]@( ████████, physik, 513534396524134420 )
[ 28/11/2018T14:53:05 ][ ROLE_ADD ]@( ████████, Physik )
[ 28/11/2018T14:53:11 ][ REACTION_ADD ]@( ████████, theo, 513534396524134420 )
[ 28/11/2018T14:53:12 ][ ROLE_ADD ]@( ████████, Theoretische Physik )
[ 28/11/2018T14:53:34 ][ REACTION_ADD ]@( ████████, exp, 513534396524134420 )
[ 28/11/2018T14:53:34 ][ ROLE_ADD ]@( ████████, Experimentalphysik )
[ 28/11/2018T14:53:45 ][ REACTION_REMOVE ]@( ████████, exp, 513534396524134420 )
[ 28/11/2018T14:53:46 ][ ROLE_REMOVE ]@( ████████, Experimentalphysik )
[ 28/11/2018T14:54:07 ][ REACTION_ADD ]@( ████████, exp, 513534396524134420 )
[ 28/11/2018T14:54:08 ][ ROLE_ADD ]@( ████████, Experimentalphysik )
[ 28/11/2018T14:54:17 ][ REACTION_ADD ]@( ████████, la, 513534396524134420 )
[ 28/11/2018T14:54:17 ][ ROLE_ADD ]@( ████████, Lineare Algebra )
```

For some mysterious reason, discord could not find the user who did react to my message on the guild, so the user **must** be a member of the guild and therefore be listed in `server.guild.member`. 
*(Assuming, the user did not leave the guild while my code was still executing his reaction which is veeery unlikely.)*

Related code:
https://github.com/ekzyis/physicsbot/blob/1fdaf4b736dac757368baa9c5b961f66559ed707/src/bot.js#L99-L105

**Comment by ekzyis** [comment]
Closing because I can reopen when issue is not solved via 6bea253

**Comment by wobbier** [comment]
I started seeing this again today

**Comment by ekzyis** [comment]
Hi @wobbier!

Are you actually using my bot or are you just creating a discord bot by yourself and stumbled across this error, too and then found this issue?

I assume the latter but nonetheless, I think your current problem can be solved by upgrading to discord.py 1.5.1 and reading about intents. I had a similar issue a few days ago when I couldn't find a member which removed a reaction. 

The solution was to upgrade to 1.5.1 and set the member intent, else you will not receive members.

Read more here: https://discordpy.readthedocs.io/en/latest/intents.html#intents-primer
